"""add link field to homework

Revision ID: 0c5403f4723e
Revises: c3a2da805b43
Create Date: 2020-12-28 10:20:57.590978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5403f4723e'
down_revision = 'c3a2da805b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework', sa.Column('link', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homework', 'link')
    # ### end Alembic commands ###
