"""Add test model

Revision ID: 43323592fb1e
Revises: 0c5403f4723e
Create Date: 2020-12-28 20:42:01.192161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43323592fb1e'
down_revision = '0c5403f4723e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_due_date'), 'test', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_due_date'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###
