"""add popup field

Revision ID: 4e5776bd17f2
Revises: 61946201688f
Create Date: 2021-02-09 09:30:19.706577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e5776bd17f2'
down_revision = '61946201688f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('popup', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'popup')
    # ### end Alembic commands ###
