"""theme selector

Revision ID: 61946201688f
Revises: a74543bda26d
Create Date: 2021-02-05 09:02:53.269488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61946201688f'
down_revision = 'a74543bda26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('theme', sa.String(length=120), nullable=True))
    op.drop_column('user', 'light_mode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('light_mode', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'theme')
    # ### end Alembic commands ###
