"""light mode toggle

Revision ID: a74543bda26d
Revises: 43323592fb1e
Create Date: 2021-02-05 08:53:39.398049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a74543bda26d"
down_revision = "43323592fb1e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("light_mode", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "light_mode")
    # ### end Alembic commands ###
