"""add classes to user model

Revision ID: c3a2da805b43
Revises: dc9f28eae189
Create Date: 2020-12-27 08:45:46.756245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3a2da805b43"
down_revision = "dc9f28eae189"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("period_10a", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_10a_zoom", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("period_10b", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_10b_zoom", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("period_1a", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_1a_zoom", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("period_1b", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_1b_zoom", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("period_2a", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_2a_zoom", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("period_2b", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_2b_zoom", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("period_3a", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_3a_zoom", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("period_3b", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_3b_zoom", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("period_4a", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_4a_zoom", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("period_4b", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_4b_zoom", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("period_5a", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_5a_zoom", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("period_5b", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_5b_zoom", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("period_6a", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_6a_zoom", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("period_6b", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_6b_zoom", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("period_7a", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_7a_zoom", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("period_7b", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_7b_zoom", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("period_8a", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_8a_zoom", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("period_8b", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_8b_zoom", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("period_9a", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_9a_zoom", sa.String(length=256), nullable=True)
    )
    op.add_column("user", sa.Column("period_9b", sa.String(length=256), nullable=True))
    op.add_column(
        "user", sa.Column("period_9b_zoom", sa.String(length=256), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "period_9b_zoom")
    op.drop_column("user", "period_9b")
    op.drop_column("user", "period_9a_zoom")
    op.drop_column("user", "period_9a")
    op.drop_column("user", "period_8b_zoom")
    op.drop_column("user", "period_8b")
    op.drop_column("user", "period_8a_zoom")
    op.drop_column("user", "period_8a")
    op.drop_column("user", "period_7b_zoom")
    op.drop_column("user", "period_7b")
    op.drop_column("user", "period_7a_zoom")
    op.drop_column("user", "period_7a")
    op.drop_column("user", "period_6b_zoom")
    op.drop_column("user", "period_6b")
    op.drop_column("user", "period_6a_zoom")
    op.drop_column("user", "period_6a")
    op.drop_column("user", "period_5b_zoom")
    op.drop_column("user", "period_5b")
    op.drop_column("user", "period_5a_zoom")
    op.drop_column("user", "period_5a")
    op.drop_column("user", "period_4b_zoom")
    op.drop_column("user", "period_4b")
    op.drop_column("user", "period_4a_zoom")
    op.drop_column("user", "period_4a")
    op.drop_column("user", "period_3b_zoom")
    op.drop_column("user", "period_3b")
    op.drop_column("user", "period_3a_zoom")
    op.drop_column("user", "period_3a")
    op.drop_column("user", "period_2b_zoom")
    op.drop_column("user", "period_2b")
    op.drop_column("user", "period_2a_zoom")
    op.drop_column("user", "period_2a")
    op.drop_column("user", "period_1b_zoom")
    op.drop_column("user", "period_1b")
    op.drop_column("user", "period_1a_zoom")
    op.drop_column("user", "period_1a")
    op.drop_column("user", "period_10b_zoom")
    op.drop_column("user", "period_10b")
    op.drop_column("user", "period_10a_zoom")
    op.drop_column("user", "period_10a")
    # ### end Alembic commands ###
